language: php

php:
  - 7.0
  - 7.1
  - 7.2

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+\.\d+$/

cache:
  directories:
    - vendor/
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "XDebug disabled."
  - composer self-update

install: 
  - cp phpunit.xml.dist phpunit.xml
  - composer install
  - composer require --dev phpstan/phpstan

script:
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml tests/
  - vendor/bin/phpstan analyse -l 7 lib/
